# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
pt:
  languageCode: pt-br
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pt

en:
  languageCode: en-us
  contentDir: content/en
  params:
    footer:
      copyright:
        notice: '@ {year} Instituto Curvelo. CNPJ 60.911.337/0001-82. This site is licensed under the {license}. All rights reserved.'
    locale:
      date_format: 'Jan 02, 2006'
      time_format: '3:04 PM'
      address_format: en-us
  menus:
    main:
      - name: R&DC
        url: rndc
        weight: 20
      - name: IO
        url: io
        weight: 21
      - name: People
        url: people
        weight: 30
      - name: Contact
        url: contact
        weight: 60

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
