# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#   - name: Notícias
#     url: post
#     weight: 20
#   - name: Projetos
#     url: project
#     weight: 25
  - name: Pessoas
    url: pessoas
    weight: 30
#   - name: Publications
#     url: publicacao
#     weight: 50
  - name: Contato
    url: contato
    weight: 60
